services:

  postgres-db:
    container_name: tester_db
    image: postgres:14.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=tester_db
    ports:
    - 5434:5432

  web:
    container_name: tester_web
    build:
      context: .
      dockerfile: ./DockerFile
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    volumes:
      - ./:/tester
    ports:
      - 8000:8000
    depends_on:
      - postgres-db
  
volumes:
  postgres_data:
